openapi: 3.0.0
info:
  description: "Blog API"
  version: "1.0.0"
  title: "Blog API"
servers:
- url: "http://localhost:80"
security: 
- bearerAuth: []
paths:
  /posts:
    post:
      tags:
      - "post"
      summary: "Creates a new post in the blog"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        200:
          description: "successful operation"
  /user:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      parameters:
      - in: "query"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/components/schemas/User"
      responses:
        default:
          description: "successful operation"
  /user/login:
    get:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      parameters:
      - name: "email"
        in: "query"
        description: "The user name for login"
        required: true
        schema:
          type: string
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        schema:
          type: string
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: string
        400:
          description: "Invalid username/password supplied"

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: "object"
      properties:
        email:
          type: "string"
        name:
          type: "string"
        password:
          type: "string"
    Post:
      type: "object"
      properties:
        title:
          type: "string"
        content:
          type: "string"




           default:
        description: "successful operation"
  /user/login:
    get:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema: 
            type: "string"
          header:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              desctiption: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              fromat: "date-time"
              description: "date in UTC when token expires"
        "400":
          description: "Invalid username/password supplied"
  definitions:
    User:
      type: "object"
      properties:
        email:
          type: "string"
        name:
          type: "string"
        password:
          type: "string"
    Post:
      type: "object"
      properties:
        title:
          type: "string"
        content:
          type: "string"